target: all

multitenancy_enabled: false

server:
  http_listen_port: 9009
  log_level: warn

common:
  storage:
    backend: filesystem
    filesystem:
      dir: /data/mimir

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /data/mimir/blocks
  tsdb:
    dir: /data/mimir/tsdb

compactor:
  data_dir: /data/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    kvstore:
      store: memberlist

ingester:
  ring:
    kvstore:
      store: memberlist
    replication_factor: 1

memberlist:
  join_members: []

limits:
  ingestion_rate: 100000
  ingestion_burst_size: 200000

ruler:
  enable_api: true
